---
- hosts: all
  environment:
    http_proxy: "http://192.168.1.1:3128"
  #remote_user: root
  become: yes
  become_method: su
  #ask_become_pass: yes
  tasks:
  - name: Ensure apache2 and php is at the latest version
    package:
      state: latest
      name: "{{item}}"
    with_items:
      - apache2
      - php
      - php-mysql
      - php-snmp
  - name: Ensure apache2 is running
    service:
      name: apache2
      state: started
      enabled: true
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  - name: Ensure apache2 is running
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
