---
- hosts: all
  vars:
    dest: distro.csv
  tasks:
    - name: Get kernel version
      shell: uname -r
      register: kversion
    - copy:
        content: ''
        dest: "{{ dest }}"
      run_once: yes
      delegate_to: 127.0.0.1
    - lineinfile:
        dest: "{{ dest }}"
        line: '{{ inventory_hostname }},{{ ansible_distribution }},{{ ansible_distribution_major_version }},{{ ansible_distribution_version }},{{ ansible_distribution_release }},{{ kversion.stdout }}'
      delegate_to: 127.0.0.1
