---
- hosts: all
  vars:
    dest: distro.csv
  tasks:
    - copy:
        content: ''
        dest: "{{ dest }}"
      run_once: yes
      delegate_to: 127.0.0.1
    - lineinfile:
        dest: "{{ dest }}"
        line: '{{ inventory_hostname }},{{ ansible_lsb.description }},{{ ansible_kernel }}'
      delegate_to: 127.0.0.1
