---
- hosts: db
  vars:
    bind_address: 0.0.0.0
  vars_files:
    - pw.yml 
  tasks:
   - name: Ensure mariadb is installed
     package:
       state: latest
       name: mariadb-server
     notify:
      - restart mariadb
   - name: Ensure mariadb is configured
     templace:
       src: ./50-server.cnf.j2
       dest: /etc/mysql/mariadb.conf.d/50-server.cnf
       backup: true
     notify:
      - restart mariadb
   - name: Ensure mariadb installation is secure
     template:
       src: ./mariadb_secure.sql.j2
       dest: /tmp/mariadb_secure.sql.j2
     shell: mysql < /tmp/mariadb_secure.sql.j2
   - name: Restart mariadb
     service:
       name: mariadb
       state: restarted
       
