---
- hosts: all
  vars:
    bind_address: 0.0.0.0
  vars_files:
    - pw_enc.yml
  tasks:
  - name: "Ensure mysql is installed"
    package:
      state: latest
      name: mysql-server
    notify:
    - Restart mysql
  - name: "Ensure mysql is configured"
    template:
      src: ./50-server.cnf.j2
      dest: /etc/mysql/mariadb.conf.d/50-server.cnf
      backup: true
    notify:
    - Restart mysql
  - name: "Ensure mysql installation is secure"
    template:
      src: ./mysql_secure.sql.j2
      dest: /tmp/mysql_secure.sql
  - name: "Execute sql"
    shell: "mysql < /tmp/mysql_secure.sql"
  - name: Cleanup
    file:
      state: absent
      path: "/tmp/mysql_secure.sql"    
  handlers: 
  - name: "Restart mysql"
    service:
      name: mysql
      state: restarted

       
